#!/usr/bin/env bash
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

nix-prefetch-git --no-deepClone --quiet \
  https://github.com/NixOS/nixpkgs-channels.git \
  refs/heads/nixos-18.03 > ${SOURCE_DIR}/../nixpkgs-version.json
