#!/usr/bin/env bash
SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

nix-prefetch-git --no-deepClone --quiet \
  https://github.com/NixOS/nixpkgs-channels.git \
  refs/heads/nixos-unstable > ${SOURCE_DIR}/../nixpkgs-unstable-version.json